version: '3.8'

services:
  whatsapp-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-bot-academia
    restart: unless-stopped
    
    environment:
      - NODE_ENV=production
      - TZ=America/Bogota
    
    volumes:
      - whatsapp_session:/app/.wwebjs_auth
      - ./logs:/app/logs
      - ./src/bot/unrecognized_queries.json:/app/src/bot/unrecognized_queries.json
      - ./public:/app/public:ro
    
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    
    networks:
      - whatsapp-net
    
    healthcheck:
      test: ["CMD-SHELL", "pgrep node || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  whatsapp_session:
    driver: local

networks:
  whatsapp-net:
    driver: bridge